# Generated by Django 2.2.4 on 2019-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Technology name')),
                ('regex', models.CharField(max_length=100, verbose_name='Regular expression')),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Page name')),
                ('url', models.CharField(max_length=200, verbose_name='Page URL')),
                ('technologies', models.ManyToManyField(blank=True, to='api.Technology')),
            ],
        ),
    ]
