# Generated by Django 2.2.4 on 2019-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='regex',
            field=models.CharField(max_length=100, verbose_name='Regular expression'),
        ),
    ]
