# Generated by Django 2.2.4 on 2019-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='technologies',
            field=models.ManyToManyField(to='api.Technology'),
        ),
    ]
