# Generated by Django 2.2.4 on 2019-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190821_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='api.Technology'),
        ),
    ]
