# Generated by Django 2.2.4 on 2019-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190823_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='technologies',
            field=models.ManyToManyField(null=True, to='api.Technology'),
        ),
    ]
